meta_product_name: "Sync"
meta_title: "Sync - Experience more streamlined collaborations"
meta_description: "We help content creators work more efficiently with clients"
meta_image: "sync.png" # should exist in `app/assets/images/`
